@startuml
left to right direction

actor usuario as u

rectangle "Financinhas" {
  usecase "Fazer Cadastro" as UC1
  usecase "Fazer Login" as UC2
  usecase "Fazer Logout" as UC3
  usecase "Cadastrar Conta" as UC4
  usecase "Editar Conta" as UC5
  usecase "Excluir Conta" as UC6
  usecase "Visualizar Contas" as UC7
  usecase "Cadastrar Categoria" as UC8
  usecase "Editar Categoria" as UC9
  usecase "Excluir Categoria" as UC10
  usecase "Visualizar Categorias" as UC11
  usecase "Registrar Receita" as UC12
  usecase "Registrar Despesa" as UC13
  usecase "Editar Transação" as UC14
  usecase "Excluir Transação" as UC15
  usecase "Visualizar Transações" as UC16
  usecase "Editar Perfil" as UC17
  usecase "Exportar Extrato CSV" as UC18
}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5
u --> UC6
u --> UC7
u --> UC8
u --> UC9
u --> UC10
u --> UC11
u --> UC12
u --> UC13
u --> UC14
u --> UC15
u --> UC16
u --> UC17
u --> UC18
@enduml
